version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - restspringerudio_data:/var/lib/postgresql/data

volumes:
  restspringerudio_data:
